# Example pipeline config
#
# Usage:
# - class: <task class name>
#   input_dir: <task input directory>
#   output_dir: <task output directory> (will be created if not existing)
#   params:
#     <name 1>: <value>
#     <name 2>: <value>

tasks:

  - class: CopyFilesTask
    input_dir: "D:\\Mosamatic\\Mosamatic Desktop 2.0\\input"
    output_dir: "D:\\Mosamatic\\Mosamatic Desktop 2.0\\copyfilestask1"
    params:

  - class: CopyFilesTask
    input_dir: "D:\\Mosamatic\\Mosamatic Desktop 2.0\\copyfilestask1"
    output_dir: "D:\\Mosamatic\\Mosamatic Desktop 2.0\\copyfilestask2"
    params:
      delay: 1