tasks:

  - class: CopyFilesTask
    input_dir: "D:\\Mosamatic\\Mosamatic Desktop 2.0\\input"
    output_dir: "D:\\Mosamatic\\Mosamatic Desktop 2.0\\copyfilestask1"
    params:

  - class: CopyFilesTask
    input_dir: "D:\\Mosamatic\\Mosamatic Desktop 2.0\\copyfilestask1"
    output_dir: "D:\\Mosamatic\\Mosamatic Desktop 2.0\\copyfilestask2"
    params: